### ISSUE TITLE
What is a motivation?

### ISSUE THREAD

**Issue by ivictbor** [mmastrac/progscrape#2]
Hi @mmastrac! Thanks for a cool project, opensource and so on! I am working with a seo a little bit, and once one of my posts goes top in reddit, I see a lot of aggregators like yours link to me. 
As a posts author I am only curios of two points:
- what is general motivation for creating such aggregator if there are a lot of competitors which do the same?
- do you apply some marketing or receive some SEO benefits from listing a links?
Just wondering because there are a lot of opinions like sites with a links might be treated as spammy from Google perspective

**Comment by mmastrac** [comment]
@ivictbor I created the project for myself and open-sourced it in case someone else wanted to play with it as well. I've been running it for about 10 years for my own use and a few hundred people also seem to make use of it. I don't get any benefits - in fact I pay out of pocket to run it without ads, but having an ad-free aggregator experience really makes my life better. :)

I'd be interested to hear how much traffic it sends your way! I don't really run analytics on this either.

**Comment by ivictbor** [comment]
@mmastrac thanks for the answer! Yepp , makes sense for me, opensource is not always beneficial. I have a couple of same projects which aim is to help people, and maybe get some small amount of back PR in exchange.
Good luck 👍
